version: 0.2

env:
  variables:
    APP_ID: "13262187"  # Set your APP_ID value here
    IMAGE_URI: "891377345891.dkr.ecr.us-east-1.amazonaws.com/sample-nodejs:latest"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 891377345891.dkr.ecr.us-east-1.amazonaws.com
      - echo Preparing to build the Docker image...
      - docker login -u uzairmansoor -p Uzair@123
      - ls -la
      - cat Dockerfile
      - echo $APP_ID
      - sed -i "s|ENV APP_ID=\".*\"|ENV APP_ID=\"$APP_ID\"|" Dockerfile
      #- sed -i 's|ENV APP_ID=".*"|ENV APP_ID="$APP_ID"|' Dockerfile  # Use the APP_ID environment variable
      - cat Dockerfile

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t sample-nodejs .
      - echo Tagging the Docker image...
      - docker tag sample-nodejs:latest $IMAGE_URI

  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $IMAGE_URI

artifacts:
  files:
    - "**/*" # Include all files as artifacts
  discard-paths: yes # Discard paths in artifacts
